### check health
GET http://localhost:3110/daily/health

### Start Meeting
POST http://localhost:3110/daily/start
Content-Type: application/json

{}

###

### End Meeting
POST http://localhost:3110/daily/end
Content-Type: application/json

{
  "meetingId": "PASTE_MEETING_ID_HERE"
}

###

### Simulate Daily Recording Webhook
POST http://localhost:3110/webhook/daily
Content-Type: application/json

{
  "payload": {
    "room_name": "test-meeting-123",
    "download_url": "https://example.com/recording.mp4"
  }
}

### Start Meeting With Bot
POST http://localhost:3110/daily/start-with-bot
Content-Type: application/json

{
  "roomName": "testRoom01-9a363039"
}
