/**
 * Project configuration
 * This file is auto-generated by pipecat-cli
 */

import type { APIRequest } from '@pipecat-ai/client-js';

export type TransportType = 'daily' | 'smallwebrtc';

export const AVAILABLE_TRANSPORTS: TransportType[] = [
  'daily',
  'smallwebrtc',
];

export const DEFAULT_TRANSPORT: TransportType = 'daily';

export const TRANSPORT_CONFIG: Record<TransportType, APIRequest> = {
  daily: {
    endpoint: '/api/start',
    requestData: {
      createDailyRoom: true,
      dailyRoomProperties: { start_video_off: true },
      transport: "daily",
    },
  },
  smallwebrtc: {
    endpoint: '/api/start',
    requestData: {
      createDailyRoom: false,
      enableDefaultIceServers: true,
      transport: "webrtc",
    },
  },
};