"""pipeCloud02 - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Groq (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""


from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.transports.daily.transport import DailyTransport, DailyParams
from pipecat.processors.aggregators.llm_context import LLMContext
from loguru import logger
from pipecat.runner.types import DailyRunnerArguments
from pipecat.audio.vad.vad_analyzer import VADParams
from dotenv import load_dotenv
import os
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.audio.turn.smart_turn.local_smart_turn_v3 import LocalSmartTurnAnalyzerV3
from pipecat.frames.frames import LLMRunFrame
from pipecat.transports.base_transport import BaseTransport
from pipecat.runner.types import RunnerArguments
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair
from pipecat.services.groq.llm import GroqLLMService
from pipecat.processors.frameworks.rtvi import RTVIObserver, RTVIProcessor, RTVIConfig
from pipecat.pipeline.task import PipelineParams, PipelineTask

load_dotenv(override=True)

import pipecat
logger.info(f"Running Pipecat {pipecat.__version__}")

async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = DeepgramSTTService(api_key=os.getenv("DEEPGRAM_API_KEY"))

    # Text-to-Speech service
    tts = CartesiaTTSService(
            api_key=os.getenv("CARTESIA_API_KEY"),
            voice_id=os.getenv("CARTESIA_VOICE_ID")
        )

    # LLM service
    llm = GroqLLMService(
            model=os.getenv("GROQ_MODEL"),
            api_key=os.getenv("GROQ_API_KEY")
        )

    messages = [
        {
            "role": "system",
            # "content": "You are a friendly AI assistant. Respond naturally and keep your answers conversational.",
            "content": (
                "You are a friendly AI assistant in a voice meeting. "
                "Keep responses natural and concise."
            ),
        },
    ]

    context = LLMContext(messages)
    context_aggregator = LLMContextAggregatorPair(context)

    # rtvi = RTVIProcessor()
    # Initialize RTVI with explicit config
    rtvi = RTVIProcessor(
        config=RTVIConfig(
            config=[
                {
                    "service": "voice_agent",
                    "options": [],
                }
            ],
            initial_config=[
                {
                    "service": "voice_agent",
                    "options": [],
                }
            ],
        )
    )


    # Pipeline - assembled from reusable components
    pipeline = Pipeline([
        transport.input(),
        rtvi,
        stt,
        context_aggregator.user(),
        llm,
        tts,
        transport.output(),
        context_aggregator.assistant(),
    ])


    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[
            RTVIObserver(rtvi),
        ],
    )

    # @rtvi.event_handler("on_client_ready")
    # async def on_client_ready(rtvi):
    #     await rtvi.set_bot_ready()
        # Kick off the conversation
        # await task.queue_frames([LLMRunFrame()])
        
    @rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        logger.info("calling set_bot_ready")
        await rtvi.set_bot_ready()
        await task.queue_frames([
            TextFrame(
                role="assistant",
                text="Hi! I'm ready whenever you'd like to start."
            )
        ])

    # @transport.event_handler("on_client_connected")
    # async def on_client_connected(transport, client):
    #     logger.info("Client connected")

    # @transport.event_handler("on_client_disconnected")
    # async def on_client_disconnected(transport, client):
    #     logger.info("Client disconnected")
    #     await task.cancel()
    
    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        if client.is_bot:
            logger.info("Bot disconnected – shutting down")
            await task.cancel()
        else:
            logger.info(f"Participant left: {client.user_name}")


    runner = PipelineRunner(handle_sigint=False)
    await runner.run(task)

async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""
    transport = None

    match runner_args:
        case DailyRunnerArguments():
            transport = DailyTransport(
                runner_args.room_url,
                runner_args.token,
                "Pipecat Bot",
                params=DailyParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                    vad_analyzer=SileroVADAnalyzer(params=VADParams(
                        stop_secs=0.5,
                        min_speech_secs=0.3,
                    )),
                    turn_analyzer=LocalSmartTurnAnalyzerV3(),
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport)

if __name__ == "__main__":
    from pipecat.runner.run import main
    main()